language: node_js
node_js:
- "10.3"
script:
- "npm run build:prod"
deploy:
  verbose: true
  on: develop
  provider: azure_web_apps
  username: azure_deployment_user
  password: azure_deployment_password
  site: azure_deployment_sitename
