language: node_js

node_js:
- "10.3"

script:
- "npm run build:prod"
- "npm test"

before_deploy:
  - mv .gitignore.prod .gitignore
  - git add build
  - git add node_modules
  - git commit -m "add build files"

deploy:
  verbose: true
  on: develop
  provider: azure_web_apps              # these environment variables are set on travis
  username: $azure_deployment_user
  password: $azure_deployment_password
  site: agileassessment-prod
