version: '3'
services:

  server:
    image: node
    volumes:
    - ./server:/usr/src/app/server
    - ./client/build:/usr/src/app/client/build
    working_dir: /usr/src/app/server
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mongo
    ports:
    - "8080:8080"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
